[package]
name = "vzmuinebot"
version = "0.9.6"
authors = ["Artem Khomenko <_mag12@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
futures = "0.3.21"
tokio = { version =  "1.20.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.9"
pretty_env_logger = "0.4.0"
teloxide = { version = "0.10.1", features = ["auto-send"] }
derive_more = "0.99.17"
strum = { version = "0.24.1", features = ["derive"] }
async-recursion = "1.0.0"

# Used to setup a webhook
warp = "0.3.2"
reqwest = "0.11.11"
serde_json = "1.0.82"

# My
smart-default = "0.6.0"
parse-display = "0.5.5"
enum-utils = "0.1.2"
chrono = "0.4.19"
text_io = "0.1.10"
runtime-fmt = "0.4.1"
arraylib = "0.3.0"
enum_default = "0.2.5"
regex = "1.6.0"
lazy_static = "1.4.0"

# Database
once_cell = "1.13.0"
tokio-postgres = { version = "0.7.6", features = ["with-chrono-0_4"] }
deadpool-postgres = "0.10.2"
postgres-native-tls = "0.5.0"
native-tls = "0.2.10"
