[package]
name = "vzmuinebot"
version = "0.2.2"
authors = ["Artem Khomenko <_mag12@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
futures = "0.3.5"
tokio = "0.2.22"
pretty_env_logger = "0.4.0"
teloxide = "0.2.0"

# Used to setup a webhook
warp = "0.2.4"
reqwest = "0.10.6"
serde_json = "1.0.56"

# My
smart-default = "0.6.0"
parse-display = "0.1.2"
enum-utils = "*"
chrono = "*"
text_io = "0.1.8"
#runtime-fmt = "0.4.0"
arraylib = "0.3.0"

# Database
once_cell = "*"
tokio-postgres = { version = "0.5.5", features = ["with-chrono-0_4"] }
deadpool-postgres = "0.5.6"
#bb8 = "0.4.2"
#bb8-postgres = "0.4.0"
