[package]
name = "vzmuinebot"
version = "0.9.5"
authors = ["Artem Khomenko <_mag12@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
futures = "0.3.15"
tokio = { version =  "1.8.1", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.7"
pretty_env_logger = "0.4.0"
teloxide = { version = "0.9.2", features = ["auto-send"] }
derive_more = "0.99.16"
strum = { version = "0.24.0", features = ["derive"] }
async-recursion = "1.0.0"

# Used to setup a webhook
warp = "0.3.1"
reqwest = "0.11.10"
serde_json = "1.0.64"

# My
smart-default = "0.6.0"
parse-display = "0.5.0"
enum-utils = "0.1.2"
chrono = "0.4.19"
text_io = "0.1.8"
#runtime-fmt = "0.4.1"
arraylib = "0.3.0"
enum_default = "0.2.5"
regex = "1.5.4"
lazy_static = "1.4.0"

# Database
once_cell = "1.8.0"
tokio-postgres = { version = "0.7.2", features = ["with-chrono-0_4"] }
deadpool-postgres = "0.10.1"
postgres-native-tls = "0.5.0"
native-tls = "0.2.7"
