[package]
name = "vzmuinebot"
version = "0.9.1"
authors = ["Artem Khomenko <_mag12@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
futures = "0.3.5"
tokio = { version =  "1.3.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.4"
pretty_env_logger = "0.4.0"
teloxide = { version = "0.4.0", features = ["auto-send"] }
teloxide-macros = "0.4.0"
derive_more = "0.99.9"
strum = { version = "0.20", features = ["derive"] }
async-recursion = "0.3.2"

# Used to setup a webhook
warp = "0.3.0"
reqwest = "0.11.2"
serde_json = "1.0.50"

# My
smart-default = "0.6.0"
parse-display = "0.5.0"
enum-utils = "*"
chrono = "0.4.15"
text_io = "0.1.8"
#runtime-fmt = "0.4.1"
arraylib = "0.3.0"
enum_default = "0.2.5"

# Database
once_cell = "1.4.1"
tokio-postgres = { version = "0.7.2", features = ["with-chrono-0_4"] }
deadpool-postgres = "0.8.0"
postgres-native-tls = "0.5.0"
native-tls = "0.2.7"
