[package]
name = "vzmuinebot"
version = "0.8.8"
authors = ["Artem Khomenko <_mag12@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
futures = "0.3.5"
tokio = { version =  "0.2.22", features = ["full"] }
pretty_env_logger = "0.4.0"
teloxide = "0.2.0"

# Used to setup a webhook
reqwest = "0.10.8"
serde_json = "1.0.57"
warp = "0.2.5"

# My
smart-default = "0.6.0"
parse-display = "0.2.0"
enum-utils = "*"
chrono = "0.4.15"
text_io = "0.1.8"
#runtime-fmt = "0.4.1"
arraylib = "0.3.0"

# Database
once_cell = "1.4.1"
tokio-postgres = { version = "0.5.5", features = ["with-chrono-0_4"] }
deadpool-postgres = "0.5.6"
postgres-native-tls = "0.3.0"
native-tls = "0.2.7"