[package]
name = "vzmuinebot"
version = "1.0.0"
authors = ["Artem Khomenko <_mag12@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
futures = "0.3.5"
tokio = "0.2.21"
pretty_env_logger = "0.4.0"
teloxide = "0.2.0"

# Used to setup a webhook
warp = "0.2.3"
reqwest = "0.10.4"
serde_json = "1.0.53"

# My
smart-default = "0.6.0"
parse-display = "0.1.2"
enum-utils = "*"
chrono = "*"
text_io = "0.1.8"
#runtime-fmt = "0.4.0"
arraylib = "0.3.0"

# Database
once_cell = "*"
tokio-postgres = { version = "0.5.4", features = ["with-chrono-0_4"] }
