# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

#--database-url postgres://postgres:Start001@localhost/diesel_demo

[print_schema]
file = "src/schema.rs"
